const LAST_UPDATE = "20200203-15:43:53"; 

const province = [
  {
    "id": 1392,
    "createTime": 1580256888000,
    "modifyTime": 1580341773000,
    "tags": "",
    "countryType": 1,
    "continents": "",
    "provinceId": "54",
    "provinceName": "西藏自治区",
    "provinceShortName": "西藏",
    "cityName": "",
    "confirmedCount": 1,
    "suspectedCount": 0,
    "curedCount": 0,
    "deadCount": 0,
    "comment": "",
    "sort": 0,
    "operator": "zhuotingting",
    "locationId": 540000
  },
  {
    "id": 30,
    "createTime": 1579663914000,
    "modifyTime": 1580617150000,
    "tags": "确诊 2 例",
    "countryType": 1,
    "continents": "",
    "provinceId": "67",
    "provinceName": "澳门",
    "provinceShortName": "澳门",
    "cityName": "",
    "confirmedCount": 8,
    "suspectedCount": 0,
    "curedCount": 0,
    "deadCount": 0,
    "comment": "",
    "sort": 23,
    "operator": "zyyun",
    "locationId": 820000
  },
  {
    "id": 24,
    "createTime": 1579617167000,
    "modifyTime": 1580475589000,
    "tags": "确诊 1 例",
    "countryType": 1,
    "continents": "",
    "provinceId": "68",
    "provinceName": "台湾",
    "provinceShortName": "台湾",
    "cityName": "",
    "confirmedCount": 10,
    "suspectedCount": 0,
    "curedCount": 0,
    "deadCount": 0,
    "comment": "",
    "sort": 27,
    "operator": "huanshi",
    "locationId": 710000
  },
  {
    "id": 182,
    "createTime": 1579860584000,
    "modifyTime": 1580697551000,
    "tags": "",
    "countryType": 1,
    "continents": "",
    "provinceId": "63",
    "provinceName": "青海省",
    "provinceShortName": "青海",
    "cityName": "",
    "confirmedCount": 13,
    "suspectedCount": 0,
    "curedCount": 0,
    "deadCount": 0,
    "comment": "",
    "sort": 40,
    "operator": "xuyt",
    "locationId": 630000
  },
  {
    "id": 25,
    "createTime": 1579617215000,
    "modifyTime": 1580687489000,
    "tags": "确诊 2 例 疑似 65 例",
    "countryType": 1,
    "continents": "",
    "provinceId": "66",
    "provinceName": "香港",
    "provinceShortName": "香港",
    "cityName": "",
    "confirmedCount": 15,
    "suspectedCount": 0,
    "curedCount": 0,
    "deadCount": 0,
    "comment": "",
    "sort": 21,
    "operator": "huanshi",
    "locationId": 810000
  },
  {
    "id": 38,
    "createTime": 1579774516000,
    "modifyTime": 1580692081000,
    "tags": "确诊 2 例 ",
    "countryType": 1,
    "continents": "",
    "provinceId": "65",
    "provinceName": "新疆维吾尔自治区",
    "provinceShortName": "新疆",
    "cityName": "",
    "confirmedCount": 24,
    "suspectedCount": 0,
    "curedCount": 0,
    "deadCount": 0,
    "comment": "",
    "sort": 24,
    "operator": "lvdong",
    "locationId": 650000
  },
  {
    "id": 16,
    "createTime": 1579598101000,
    "modifyTime": 1580696829000,
    "tags": "确诊 1 例",
    "countryType": 1,
    "continents": "",
    "provinceId": "64",
    "provinceName": "宁夏回族自治区",
    "provinceShortName": "宁夏",
    "cityName": "",
    "confirmedCount": 31,
    "suspectedCount": 0,
    "curedCount": 0,
    "deadCount": 0,
    "comment": "",
    "sort": 31,
    "operator": "zyyun",
    "locationId": 640000
  },
  {
    "id": 17,
    "createTime": 1579598339000,
    "modifyTime": 1580690485000,
    "tags": "确诊 1 例",
    "countryType": 1,
    "continents": "",
    "provinceId": "22",
    "provinceName": "吉林省",
    "provinceShortName": "吉林",
    "cityName": "",
    "confirmedCount": 31,
    "suspectedCount": 0,
    "curedCount": 1,
    "deadCount": 0,
    "comment": "",
    "sort": 29,
    "operator": "zyyun",
    "locationId": 220000
  },
  {
    "id": 36,
    "createTime": 1579754908000,
    "modifyTime": 1580698377000,
    "tags": "疑似 1 例",
    "countryType": 1,
    "continents": "",
    "provinceId": "15",
    "provinceName": "内蒙古自治区",
    "provinceShortName": "内蒙古",
    "cityName": "",
    "confirmedCount": 34,
    "suspectedCount": 0,
    "curedCount": 1,
    "deadCount": 0,
    "comment": "",
    "sort": 32,
    "operator": "huanshi",
    "locationId": 150000
  },
  {
    "id": 12,
    "createTime": 1579588572000,
    "modifyTime": 1580691509000,
    "tags": "确诊 3 例",
    "countryType": 1,
    "continents": "",
    "provinceId": "52",
    "provinceName": "贵州省",
    "provinceShortName": "贵州",
    "cityName": "",
    "confirmedCount": 46,
    "suspectedCount": 0,
    "curedCount": 2,
    "deadCount": 0,
    "comment": "",
    "sort": 19,
    "operator": "caoyang",
    "locationId": 520000
  },
  {
    "id": 37,
    "createTime": 1579757757000,
    "modifyTime": 1580686384000,
    "tags": "确诊 2 例",
    "countryType": 1,
    "continents": "",
    "provinceId": "62",
    "provinceName": "甘肃省",
    "provinceShortName": "甘肃",
    "cityName": "",
    "confirmedCount": 51,
    "suspectedCount": 0,
    "curedCount": 3,
    "deadCount": 0,
    "comment": "",
    "sort": 25,
    "operator": "huanshi",
    "locationId": 620000
  },
  {
    "id": 20,
    "createTime": 1579604600000,
    "modifyTime": 1580709567000,
    "tags": "确诊 4 例",
    "countryType": 1,
    "continents": "",
    "provinceId": "12",
    "provinceName": "天津市",
    "provinceShortName": "天津",
    "cityName": "",
    "confirmedCount": 56,
    "suspectedCount": 0,
    "curedCount": 1,
    "deadCount": 0,
    "comment": "待明确地区 : 治愈 1",
    "sort": 16,
    "operator": "zyyun",
    "locationId": 120000
  },
  {
    "id": 31,
    "createTime": 1579682845000,
    "modifyTime": 1580699592000,
    "tags": "确诊 1 例",
    "countryType": 1,
    "continents": "",
    "provinceId": "14",
    "provinceName": "山西省",
    "provinceShortName": "山西",
    "cityName": "",
    "confirmedCount": 66,
    "suspectedCount": 0,
    "curedCount": 2,
    "deadCount": 0,
    "comment": "",
    "sort": 28,
    "operator": "lvdong",
    "locationId": 140000
  },
  {
    "id": 15,
    "createTime": 1579598057000,
    "modifyTime": 1580697583000,
    "tags": "确诊 5 例，疑似 32 例",
    "countryType": 1,
    "continents": "",
    "provinceId": "46",
    "provinceName": "海南省",
    "provinceShortName": "海南",
    "cityName": "",
    "confirmedCount": 71,
    "suspectedCount": 0,
    "curedCount": 4,
    "deadCount": 1,
    "comment": "",
    "sort": 15,
    "operator": "zyyun",
    "locationId": 460000
  },
  {
    "id": 29,
    "createTime": 1579656427000,
    "modifyTime": 1580702208000,
    "tags": "确诊 3 例",
    "countryType": 1,
    "continents": "",
    "provinceId": "21",
    "provinceName": "辽宁省",
    "provinceShortName": "辽宁",
    "cityName": "",
    "confirmedCount": 73,
    "suspectedCount": 0,
    "curedCount": 1,
    "deadCount": 0,
    "comment": "",
    "sort": 20,
    "operator": "caoyang",
    "locationId": 210000
  },
  {
    "id": 5,
    "createTime": 1579542213000,
    "modifyTime": 1580710237000,
    "tags": "确诊 2 例",
    "countryType": 1,
    "continents": "",
    "provinceId": "53",
    "provinceName": "云南省",
    "provinceShortName": "云南",
    "cityName": "",
    "confirmedCount": 109,
    "suspectedCount": 0,
    "curedCount": 3,
    "deadCount": 0,
    "comment": "",
    "sort": 26,
    "operator": "zhanglifeng",
    "locationId": 530000
  },
  {
    "id": 33,
    "createTime": 1579705215000,
    "modifyTime": 1580689215000,
    "tags": "确诊 1 例，死亡 1 例",
    "countryType": 1,
    "continents": "",
    "provinceId": "13",
    "provinceName": "河北省",
    "provinceShortName": "河北",
    "cityName": "",
    "confirmedCount": 113,
    "suspectedCount": 0,
    "curedCount": 3,
    "deadCount": 1,
    "comment": "",
    "sort": 30,
    "operator": "dongyang",
    "locationId": 130000
  },
  {
    "id": 26,
    "createTime": 1579621178000,
    "modifyTime": 1580713733000,
    "tags": "确诊 2 例",
    "countryType": 1,
    "continents": "",
    "provinceId": "23",
    "provinceName": "黑龙江省",
    "provinceShortName": "黑龙江",
    "cityName": "",
    "confirmedCount": 121,
    "suspectedCount": 0,
    "curedCount": 2,
    "deadCount": 2,
    "comment": "",
    "sort": 22,
    "operator": "huanshi",
    "locationId": 230000
  },
  {
    "id": 7,
    "createTime": 1579542254000,
    "modifyTime": 1580688770000,
    "tags": "确诊 5 例",
    "countryType": 1,
    "continents": "",
    "provinceId": "45",
    "provinceName": "广西壮族自治区",
    "provinceShortName": "广西",
    "cityName": "",
    "confirmedCount": 127,
    "suspectedCount": 0,
    "curedCount": 2,
    "deadCount": 0,
    "comment": "",
    "sort": 11,
    "operator": "zhanglifeng",
    "locationId": 450000
  },
  {
    "id": 35,
    "createTime": 1579745445000,
    "modifyTime": 1580697020000,
    "tags": "确诊 5 例 疑似 1 例",
    "countryType": 1,
    "continents": "",
    "provinceId": "61",
    "provinceName": "陕西省",
    "provinceShortName": "陕西",
    "cityName": "",
    "confirmedCount": 128,
    "suspectedCount": 0,
    "curedCount": 0,
    "deadCount": 0,
    "comment": "",
    "sort": 18,
    "operator": "zyyun",
    "locationId": 610000
  },
  {
    "id": 32,
    "createTime": 1579688286000,
    "modifyTime": 1580699758000,
    "tags": "确诊 5 例 疑似 2 例",
    "countryType": 1,
    "continents": "",
    "provinceId": "35",
    "provinceName": "福建省",
    "provinceShortName": "福建",
    "cityName": "",
    "confirmedCount": 179,
    "suspectedCount": 0,
    "curedCount": 0,
    "deadCount": 0,
    "comment": "",
    "sort": 12,
    "operator": "dengyuguo",
    "locationId": 350000
  },
  {
    "id": 2,
    "createTime": 1579542158000,
    "modifyTime": 1580632335000,
    "tags": "确诊 22 例 ",
    "countryType": 1,
    "continents": "",
    "provinceId": "11",
    "provinceName": "北京市",
    "provinceShortName": "北京",
    "cityName": "",
    "confirmedCount": 191,
    "suspectedCount": 0,
    "curedCount": 9,
    "deadCount": 1,
    "comment": "待明确地区：死亡 1，治愈 5",
    "sort": 4,
    "operator": "zhanglifeng",
    "locationId": 110000
  },
  {
    "id": 6,
    "createTime": 1579542231000,
    "modifyTime": 1580711094000,
    "tags": "确诊 16 例，疑似 22 例",
    "countryType": 1,
    "continents": "",
    "provinceId": "31",
    "provinceName": "上海市",
    "provinceShortName": "上海",
    "cityName": "",
    "confirmedCount": 203,
    "suspectedCount": 0,
    "curedCount": 10,
    "deadCount": 1,
    "comment": "治愈数据统一归属上海市公卫临床中心，暂无具体分区",
    "sort": 5,
    "operator": "zhanglifeng",
    "locationId": 310000
  },
  {
    "id": 4,
    "createTime": 1579542193000,
    "modifyTime": 1580691718000,
    "tags": "确诊 8 例，疑似 2 例",
    "countryType": 1,
    "continents": "",
    "provinceId": "51",
    "provinceName": "四川省",
    "provinceShortName": "四川",
    "cityName": "",
    "confirmedCount": 254,
    "suspectedCount": 0,
    "curedCount": 12,
    "deadCount": 1,
    "comment": "待明确地区：治愈 1",
    "sort": 9,
    "operator": "zhanglifeng",
    "locationId": 510000
  },
  {
    "id": 8,
    "createTime": 1579542291000,
    "modifyTime": 1580714815000,
    "tags": "确诊 6 例， 疑似 2 例",
    "countryType": 1,
    "continents": "",
    "provinceId": "37",
    "provinceName": "山东省",
    "provinceShortName": "山东",
    "cityName": "",
    "confirmedCount": 259,
    "suspectedCount": 0,
    "curedCount": 6,
    "deadCount": 0,
    "comment": "",
    "sort": 10,
    "operator": "zhanglifeng",
    "locationId": 370000
  },
  {
    "id": 34,
    "createTime": 1579709672000,
    "modifyTime": 1580691509000,
    "tags": "确诊 5 例",
    "countryType": 1,
    "continents": "",
    "provinceId": "32",
    "provinceName": "江苏省",
    "provinceShortName": "江苏",
    "cityName": "",
    "confirmedCount": 271,
    "suspectedCount": 0,
    "curedCount": 7,
    "deadCount": 0,
    "comment": "",
    "sort": 13,
    "operator": "huanshi",
    "locationId": 320000
  },
  {
    "id": 22,
    "createTime": 1579612635000,
    "modifyTime": 1580686218000,
    "tags": "确诊 9 例",
    "countryType": 1,
    "continents": "",
    "provinceId": "50",
    "provinceName": "重庆市",
    "provinceShortName": "重庆",
    "cityName": "",
    "confirmedCount": 300,
    "suspectedCount": 0,
    "curedCount": 7,
    "deadCount": 2,
    "comment": "",
    "sort": 8,
    "operator": "huanshi",
    "locationId": 500000
  },
  {
    "id": 18,
    "createTime": 1579598380000,
    "modifyTime": 1580693481000,
    "tags": "确诊 7 例",
    "countryType": 1,
    "continents": "",
    "provinceId": "36",
    "provinceName": "江西省",
    "provinceShortName": "江西",
    "cityName": "",
    "confirmedCount": 391,
    "suspectedCount": 0,
    "curedCount": 18,
    "deadCount": 0,
    "comment": "",
    "sort": 17,
    "operator": "zyyun",
    "locationId": 360000
  },
  {
    "id": 14,
    "createTime": 1579598038000,
    "modifyTime": 1580703686000,
    "tags": "确诊 9 例，疑似 4 例",
    "countryType": 1,
    "continents": "",
    "provinceId": "34",
    "provinceName": "安徽省",
    "provinceShortName": "安徽",
    "cityName": "",
    "confirmedCount": 408,
    "suspectedCount": 0,
    "curedCount": 8,
    "deadCount": 0,
    "comment": "",
    "sort": 7,
    "operator": "zyyun",
    "locationId": 340000
  },
  {
    "id": 27,
    "createTime": 1579623404000,
    "modifyTime": 1580693431000,
    "tags": "确诊 24 例",
    "countryType": 1,
    "continents": "",
    "provinceId": "43",
    "provinceName": "湖南省",
    "provinceShortName": "湖南",
    "cityName": "",
    "confirmedCount": 521,
    "suspectedCount": 0,
    "curedCount": 16,
    "deadCount": 0,
    "comment": "",
    "sort": 6,
    "operator": "huanshi",
    "locationId": 430000
  },
  {
    "id": 21,
    "createTime": 1579607817000,
    "modifyTime": 1580691355000,
    "tags": "确诊 5 例",
    "countryType": 1,
    "continents": "",
    "provinceId": "41",
    "provinceName": "河南省",
    "provinceShortName": "河南",
    "cityName": "",
    "confirmedCount": 566,
    "suspectedCount": 0,
    "curedCount": 14,
    "deadCount": 2,
    "comment": "待明确地区：治愈 6",
    "sort": 14,
    "operator": "huanshi",
    "locationId": 410000
  },
  {
    "id": 3,
    "createTime": 1579542174000,
    "modifyTime": 1580693431000,
    "tags": "确诊 32 例，疑似 1 例，治愈 2 例",
    "countryType": 1,
    "continents": "",
    "provinceId": "44",
    "provinceName": "广东省",
    "provinceShortName": "广东",
    "cityName": "",
    "confirmedCount": 683,
    "suspectedCount": 0,
    "curedCount": 15,
    "deadCount": 0,
    "comment": "",
    "sort": 2,
    "operator": "zhanglifeng",
    "locationId": 440000
  },
  {
    "id": 10,
    "createTime": 1579546399000,
    "modifyTime": 1580693346000,
    "tags": "确诊 27 例",
    "countryType": 1,
    "continents": "",
    "provinceId": "33",
    "provinceName": "浙江省",
    "provinceShortName": "浙江",
    "cityName": "",
    "confirmedCount": 724,
    "suspectedCount": 0,
    "curedCount": 36,
    "deadCount": 0,
    "comment": "",
    "sort": 3,
    "operator": "heyanan",
    "locationId": 330000
  },
  {
    "id": 1,
    "createTime": 1579538652000,
    "modifyTime": 1580688140000,
    "tags": "确诊 444 例，疑似病例数待确认，治愈 28 例，死亡 17 例",
    "countryType": 1,
    "continents": "",
    "provinceId": "42",
    "provinceName": "湖北省",
    "provinceShortName": "湖北",
    "cityName": "",
    "confirmedCount": 11177,
    "suspectedCount": 0,
    "curedCount": 295,
    "deadCount": 350,
    "comment": "待明确地区：治愈 1",
    "sort": 1,
    "operator": "zhanglifeng",
    "locationId": 420000
  }
]; 

const world = [
  {
    "id": 953,
    "createTime": 1580027704000,
    "modifyTime": 1580561200000,
    "tags": "",
    "countryType": 2,
    "continents": "亚洲",
    "provinceId": "6",
    "provinceName": "日本",
    "provinceShortName": "",
    "cityName": "",
    "confirmedCount": 20,
    "suspectedCount": 0,
    "curedCount": 1,
    "deadCount": 0,
    "comment": "",
    "sort": 0,
    "operator": "xuyt",
    "locationId": 951002
  },
  {
    "id": 949,
    "createTime": 1580027637000,
    "modifyTime": 1580495765000,
    "tags": "",
    "countryType": 2,
    "continents": "亚洲",
    "provinceId": "2",
    "provinceName": "泰国",
    "provinceShortName": "",
    "cityName": "",
    "confirmedCount": 19,
    "suspectedCount": 0,
    "curedCount": 5,
    "deadCount": 0,
    "comment": "",
    "sort": 0,
    "operator": "xuyt",
    "locationId": 952010
  },
  {
    "id": 950,
    "createTime": 1580027655000,
    "modifyTime": 1580619404000,
    "tags": "",
    "countryType": 2,
    "continents": "亚洲",
    "provinceId": "3",
    "provinceName": "新加坡",
    "provinceShortName": "",
    "cityName": "",
    "confirmedCount": 18,
    "suspectedCount": 0,
    "curedCount": 0,
    "deadCount": 0,
    "comment": "",
    "sort": 0,
    "operator": "xuyt",
    "locationId": 952009
  },
  {
    "id": 954,
    "createTime": 1580027721000,
    "modifyTime": 1580609979000,
    "tags": "",
    "countryType": 2,
    "continents": "亚洲",
    "provinceId": "7",
    "provinceName": "韩国",
    "provinceShortName": "",
    "cityName": "",
    "confirmedCount": 15,
    "suspectedCount": 0,
    "curedCount": 0,
    "deadCount": 0,
    "comment": "",
    "sort": 0,
    "operator": "xuyt",
    "locationId": 951004
  },
  {
    "id": 958,
    "createTime": 1580027777000,
    "modifyTime": 1580620070000,
    "tags": "",
    "countryType": 2,
    "continents": "大洋洲",
    "provinceId": "10",
    "provinceName": "澳大利亚",
    "provinceShortName": "",
    "cityName": "",
    "confirmedCount": 12,
    "suspectedCount": 0,
    "curedCount": 2,
    "deadCount": 0,
    "comment": "",
    "sort": 0,
    "operator": "xuyt",
    "locationId": 990001
  },
  {
    "id": 1047,
    "createTime": 1580167302000,
    "modifyTime": 1580653589000,
    "tags": "",
    "countryType": 2,
    "continents": "欧洲",
    "provinceId": "10",
    "provinceName": "德国",
    "provinceShortName": "",
    "cityName": "",
    "confirmedCount": 10,
    "suspectedCount": 0,
    "curedCount": 0,
    "deadCount": 0,
    "comment": "",
    "sort": 0,
    "operator": "shiweiyi",
    "locationId": 963003
  },
  {
    "id": 955,
    "createTime": 1580027735000,
    "modifyTime": 1580684415000,
    "tags": "",
    "countryType": 2,
    "continents": "北美洲",
    "provinceId": "8",
    "provinceName": "美国",
    "provinceShortName": "",
    "cityName": "",
    "confirmedCount": 9,
    "suspectedCount": 0,
    "curedCount": 0,
    "deadCount": 0,
    "comment": "",
    "sort": 0,
    "operator": "xuyt",
    "locationId": 971002
  },
  {
    "id": 951,
    "createTime": 1580027668000,
    "modifyTime": 1580495813000,
    "tags": "",
    "countryType": 2,
    "continents": "亚洲",
    "provinceId": "4",
    "provinceName": "马来西亚",
    "provinceShortName": "",
    "cityName": "",
    "confirmedCount": 8,
    "suspectedCount": 0,
    "curedCount": 0,
    "deadCount": 0,
    "comment": "",
    "sort": 0,
    "operator": "xuyt",
    "locationId": 952007
  },
  {
    "id": 952,
    "createTime": 1580027683000,
    "modifyTime": 1580516875000,
    "tags": "",
    "countryType": 2,
    "continents": "欧洲",
    "provinceId": "5",
    "provinceName": "法国",
    "provinceShortName": "",
    "cityName": "",
    "confirmedCount": 6,
    "suspectedCount": 0,
    "curedCount": 0,
    "deadCount": 0,
    "comment": "",
    "sort": 0,
    "operator": "xuyt",
    "locationId": 961002
  },
  {
    "id": 956,
    "createTime": 1580027751000,
    "modifyTime": 1580539329000,
    "tags": "",
    "countryType": 2,
    "continents": "亚洲",
    "provinceId": "9",
    "provinceName": "越南",
    "provinceShortName": "",
    "cityName": "",
    "confirmedCount": 6,
    "suspectedCount": 0,
    "curedCount": 1,
    "deadCount": 0,
    "comment": "",
    "sort": 0,
    "operator": "xuyt",
    "locationId": 952011
  },
  {
    "id": 1650,
    "createTime": 1580276720000,
    "modifyTime": 1580621660000,
    "tags": "",
    "countryType": 2,
    "continents": "亚洲",
    "provinceId": "10",
    "provinceName": "阿联酋",
    "provinceShortName": "",
    "cityName": "",
    "confirmedCount": 5,
    "suspectedCount": 0,
    "curedCount": 0,
    "deadCount": 0,
    "comment": "",
    "sort": 0,
    "operator": "yuting",
    "locationId": 955019
  },
  {
    "id": 959,
    "createTime": 1580027795000,
    "modifyTime": 1580552879000,
    "tags": "",
    "countryType": 2,
    "continents": "北美洲",
    "provinceId": "10",
    "provinceName": "加拿大",
    "provinceShortName": "",
    "cityName": "",
    "confirmedCount": 4,
    "suspectedCount": 0,
    "curedCount": 0,
    "deadCount": 0,
    "comment": "",
    "sort": 0,
    "operator": "xuyt",
    "locationId": 971001
  },
  {
    "id": 1954,
    "createTime": 1580375521000,
    "modifyTime": 1580622802000,
    "tags": "",
    "countryType": 2,
    "continents": "亚洲",
    "provinceId": "10",
    "provinceName": "印度",
    "provinceShortName": "",
    "cityName": "",
    "confirmedCount": 2,
    "suspectedCount": 0,
    "curedCount": 0,
    "deadCount": 0,
    "comment": "",
    "sort": 0,
    "operator": "gaoh",
    "locationId": 953003
  },
  {
    "id": 1957,
    "createTime": 1580425693000,
    "modifyTime": 1580516912000,
    "tags": "",
    "countryType": 2,
    "continents": "欧洲",
    "provinceId": "10",
    "provinceName": "意大利",
    "provinceShortName": "",
    "cityName": "",
    "confirmedCount": 2,
    "suspectedCount": 0,
    "curedCount": 0,
    "deadCount": 0,
    "comment": "",
    "sort": 0,
    "operator": "shiweiyi",
    "locationId": 965008
  },
  {
    "id": 2280,
    "createTime": 1580464639000,
    "modifyTime": 1580495938000,
    "tags": "",
    "countryType": 2,
    "continents": "欧洲",
    "provinceId": "10",
    "provinceName": "英国",
    "provinceShortName": "",
    "cityName": "",
    "confirmedCount": 2,
    "suspectedCount": 0,
    "curedCount": 0,
    "deadCount": 0,
    "comment": "",
    "sort": 0,
    "operator": "leimanman",
    "locationId": 961007
  },
  {
    "id": 2281,
    "createTime": 1580476133000,
    "modifyTime": 1580495947000,
    "tags": "",
    "countryType": 2,
    "continents": "欧洲",
    "provinceId": "10",
    "provinceName": "俄罗斯",
    "provinceShortName": "",
    "cityName": "",
    "confirmedCount": 2,
    "suspectedCount": 0,
    "curedCount": 0,
    "deadCount": 0,
    "comment": "",
    "sort": 0,
    "operator": "hekaiqi",
    "locationId": 964006
  },
  {
    "id": 2870,
    "createTime": 1580566796000,
    "modifyTime": 1580614212000,
    "tags": "",
    "countryType": 2,
    "continents": "亚洲",
    "provinceId": "10",
    "provinceName": "菲律宾",
    "provinceShortName": "",
    "cityName": "",
    "confirmedCount": 2,
    "suspectedCount": 0,
    "curedCount": 0,
    "deadCount": 1,
    "comment": "",
    "sort": 0,
    "operator": "hekaiqi",
    "locationId": 952008
  },
  {
    "id": 957,
    "createTime": 1580027764000,
    "modifyTime": 1580495955000,
    "tags": "",
    "countryType": 2,
    "continents": "亚洲",
    "provinceId": "10",
    "provinceName": "尼泊尔",
    "provinceShortName": "",
    "cityName": "",
    "confirmedCount": 1,
    "suspectedCount": 0,
    "curedCount": 0,
    "deadCount": 0,
    "comment": "",
    "sort": 0,
    "operator": "xuyt",
    "locationId": 953005
  },
  {
    "id": 1023,
    "createTime": 1580130061000,
    "modifyTime": 1580495965000,
    "tags": "",
    "countryType": 2,
    "continents": "亚洲",
    "provinceId": "10",
    "provinceName": "柬埔寨",
    "provinceShortName": "",
    "cityName": "",
    "confirmedCount": 1,
    "suspectedCount": 0,
    "curedCount": 0,
    "deadCount": 0,
    "comment": "",
    "sort": 0,
    "operator": "hanting",
    "locationId": 952003
  },
  {
    "id": 1306,
    "createTime": 1580182019000,
    "modifyTime": 1580495982000,
    "tags": "",
    "countryType": 2,
    "continents": "亚洲",
    "provinceId": "10",
    "provinceName": "斯里兰卡",
    "provinceShortName": "",
    "cityName": "",
    "confirmedCount": 1,
    "suspectedCount": 0,
    "curedCount": 0,
    "deadCount": 0,
    "comment": "",
    "sort": 0,
    "operator": "zhuotingting",
    "locationId": 953007
  },
  {
    "id": 1656,
    "createTime": 1580337882000,
    "modifyTime": 1580495991000,
    "tags": "",
    "countryType": 2,
    "continents": "欧洲",
    "provinceId": "10",
    "provinceName": "芬兰",
    "provinceShortName": "",
    "cityName": "",
    "confirmedCount": 1,
    "suspectedCount": 0,
    "curedCount": 0,
    "deadCount": 0,
    "comment": "",
    "sort": 0,
    "operator": "zhuotingting",
    "locationId": 962002
  },
  {
    "id": 2293,
    "createTime": 1580512517000,
    "modifyTime": 1580514491000,
    "tags": "",
    "countryType": 2,
    "continents": "欧洲",
    "provinceId": "10",
    "provinceName": "西班牙",
    "provinceShortName": "",
    "cityName": "",
    "confirmedCount": 1,
    "suspectedCount": 0,
    "curedCount": 0,
    "deadCount": 0,
    "comment": "",
    "sort": 0,
    "operator": "zhuotingting",
    "locationId": 965015
  },
  {
    "id": 2596,
    "createTime": 1580516851000,
    "modifyTime": 1580516851000,
    "tags": "",
    "countryType": 2,
    "continents": "欧洲",
    "provinceId": "10",
    "provinceName": "瑞典",
    "provinceShortName": "",
    "cityName": "",
    "confirmedCount": 1,
    "suspectedCount": 0,
    "curedCount": 0,
    "deadCount": 0,
    "comment": "",
    "sort": 0,
    "operator": "leimanman",
    "locationId": 962005
  }
]; 

